language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11

env:
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.7
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.8
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.9

install: true

script: mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
